stark:
  account:
    environment: ${ZONE:local}
    id: ${ID_ACCOUNT:0000000000}
    key: ${KEY:local}
quarkus:
  hibernate-orm:
    database:
      generation: none
  datasource:
    jdbc:
      url: ${DATABASE_URL:urlDoBanco_schema}
    db-kind: postgresql
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
kafka:
  bootstrap:
    servers: localhost:9092
mp:
  messaging:
    incoming:
      challenge:
        connector: smallrye-kafka
        topic: intention-transfer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer