quarkus:
  datasource:
    jdbc:
      url: ${DATABASE_URL:urlDoBanco_schema}
    db-kind: postgresql
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
kafka:
  bootstrap:
    servers: kafka:9092
mp:
  messaging:
    incoming:
      challenge:
        connector: smallrye-kafka
        topic: intention-transfer